# Generated by Django 4.0.1 on 2024-12-01 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_task', '0004_alter_sdg_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertask',
            name='files_uploaded',
        ),
        migrations.CreateModel(
            name='UserTaskFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('files_uploaded', models.FileField(upload_to='user-task/files/')),
                ('user_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_task.usertask')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
