# Generated by Django 4.0.1 on 2024-12-01 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_task', '0005_remove_usertask_files_uploaded_usertaskfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertaskfile',
            name='user_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files_uploaded', to='user_task.usertask'),
        ),
    ]
