# Generated by Django 4.0.1 on 2024-12-01 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_task', '0006_alter_usertaskfile_user_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertaskfile',
            old_name='files_uploaded',
            new_name='file',
        ),
    ]
