# Generated by Django 4.0.1 on 2024-12-22 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_task', '0007_rename_files_uploaded_usertaskfile_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='max_limit_complete',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
