# Generated by Django 4.0.1 on 2024-12-22 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_task', '0008_task_max_limit_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_verification_required',
            field=models.BooleanField(default=False),
        ),
    ]
