# Generated by Django 4.0.1 on 2024-12-25 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_task', '0011_rename_taskbookmark_usertaskbookmark_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sdg',
            name='sdg_number',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
