# Generated by Django 4.0.1 on 2024-12-28 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_task', '0012_sdg_sdg_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertaskreward',
            name='task',
        ),
        migrations.AddField(
            model_name='usertaskreward',
            name='user_task',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='user_task.usertask'),
            preserve_default=False,
        ),
    ]
