# Generated by Django 4.0.1 on 2025-04-14 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_task', '0013_remove_usertaskreward_task_usertaskreward_user_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='task-category/'),
        ),
    ]
