# Generated by Django 4.0.1 on 2025-05-15 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_task', '0014_taskcategory_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='image',
            field=models.ImageField(null=True, upload_to='task/image'),
        ),
    ]
