# Generated by Django 4.0.1 on 2024-12-28 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpost',
            old_name='task',
            new_name='user_task',
        ),
    ]
