# Generated by Django 4.0.1 on 2024-11-29 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_company_user_user_type_userprofile_userpost_and_more'),
        ('challenge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_challenges', to='user.company'),
        ),
        migrations.AddField(
            model_name='userchallengejoining',
            name='points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
