# Generated by Django 4.0.1 on 2024-12-15 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_postreact_unique_together_and_more'),
        ('challenge', '0003_challenge_challenge_expiry_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_challenges', to='user.company'),
        ),
    ]
