# Generated by Django 4.0.1 on 2024-12-22 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0004_alter_challenge_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskchallenge',
            name='task_max_limit',
            field=models.PositiveIntegerField(default=3),
        ),
    ]
