# Generated by Django 4.0.1 on 2025-05-18 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0006_challengeimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengeimage',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
