# Generated by Django 4.0.1 on 2024-12-15 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reward', '0003_rename_redeemedpoint_redeempoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftvoucher',
            name='company_reward',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reward.companyreward'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productcard',
            name='company_reward',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reward.companyreward'),
            preserve_default=False,
        ),
    ]
