# Generated by Django 4.0.1 on 2024-12-01 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_company_user_user_type_userprofile_userpost_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='postreact',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='postreact',
            name='post',
        ),
        migrations.RemoveField(
            model_name='postreact',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userpost',
            name='task',
        ),
        migrations.RemoveField(
            model_name='userpost',
            name='user',
        ),
        migrations.DeleteModel(
            name='PostComment',
        ),
        migrations.DeleteModel(
            name='PostReact',
        ),
        migrations.DeleteModel(
            name='UserPost',
        ),
    ]
