# Generated by Django 4.0.1 on 2024-12-28 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_company_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='total_points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
